import Head from 'next/head'
import Image from 'next/image'
import Customer from '../components/Customer'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Refer from '../components/Level'
import Promo from '../components/Promo'
import Works from '../components/Works'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Azany</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Refer />
      <Promo />
      <Customer/>
      <Works/> 
      <Footer/>
    </div>
  )
}
